### PR TITLE
A5 AR - Matthew Heinz & Roxanne El Baff

### PR DESCRIPTION
**Pull request by roxanneelbaff**
Assignment 5 AR
Matthew Heinz   115270
Roxanne El Baff 115185

### CODE REVIEW

**Comment by Tidebreaker** [comment]
I somehow can't see anything over the shields other than a white plane. What should I see?

**Comment by roxanneelbaff** [comment]
Hi,
You should see the webpage related to the image

**Comment by roxanneelbaff** [comment]
Hi again,
I thought it's worth mentioning that Matthew and I have the same mobile device (THL) so we only tested it on 1 device and it was working. Could this be the reason why it's not working properly on yours?

**Comment by Tidebreaker** [comment]
It's very hard to tell, actually. Android development is no easy task, especially because of the variety of devices there are, the huge vastness of specifications within the devices and even within which devices run which OS, which additional hardware like SD cards are installed and what not. On top of that, Android (as opposed to iOS) has a very loose standard as to how code is supposed to look and work.

For all I know, the code looks good. The white plane can be reason of anything, may that be the device, a louse internet connection on my side or a server down on the University's side, I can't tell. Don't worry, as I said, the code looks good and it basically does what it's supposed to, so I'm absolutely fine with that.

**Comment by roxanneelbaff** [comment]
Makes sense. (y)

**Pull request closed without merging**
